### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Hua-Zhou** [OpenMendel/VCFTools.jl#1]
This issue documents the implementation roadmap for iterative solvers.

- [x] Convert GT data to Plink format (SnpData)
- [x] Subset VCF records according chromosome and position range
- [x] Subset VCF records according to marker index or IDs
- [x] Subset VCF samples according to individual index or names
- [ ] Convert methods for VCF.Reader, e.g., `convert(Matrix{T}, reader::VCF.Reader)` will convert all records from the current position of `reader` to a matrix of type `Matrix{T}`  
- [ ] Copy methods for VCF.Reader, e.g., `copy(A::AbstractMatrix{T}, reader::VCF.Reader)` will fill the columns of `A` the GT data from the current position of `reader`

**Comment by biona001** [comment]
Below is a (tentative) list of features I need for MendelImpute:
- [x] `filter` function based on sample and record index
- [x] `convert_ht` function to import VCF files into a numeric matrix where columns are haplotypes
- [x] `convert_ds` function to read dosage into a numeric matrix
- [x] `convert_vcf` function to convert phased genotype matrix back to a VCF file. **This is not implemented explicitly but is support with general `write` methods. See MendelImpute's `impute.jl`**

 I will try to implement them in the next 1~2 weeks.. Are there any caveats I need to be aware of? In particular, I'm not sure what is the best way to filter based on sample index due to the data structure of `VCF.Record`.

**Comment by biona001** [comment]
Here are a few more desired routines typically needed for quality control:

- [ ] splitting multi-allelic calls into different records
- [ ] left-aligning indels
- [ ] removing 'junk' variants that have a high statistical probability of being false-positives via the QUAL score, which is negative log 10 Phred-scaled quality.

They are mentioned [here](https://www.biostars.org/p/355488/)

**Comment by kose-y** [comment]
see https://github.com/vcftools/vcftools/blob/master/src/cpp/variant_file_format_convert.cpp for vcf to plink conversion.

**Comment by kose-y** [comment]
VCF to PLINK is implemented in SnpArrays.jl.

**Comment by biona001** [comment]
In the next few days, I will add:
- [ ] Calculation of Hardy Wienburg equilibrium p-value using Fisher's exact test ([reference](https://www.sciencedirect.com/science/article/pii/S0002929707607356))
- [ ] GRM calculation, with emphasis on treating missing data ([reference](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6220858/))

**Comment by Hua-Zhou** [comment]
👍
